# spring.application.name=lets-play
# # Enable H2 console
# spring.h2.console.enabled=true 
# #JDBC URL for H2 db
# # spring.datasource.url=jdbc:h2:mem:testdb

 

# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# # JPA (Hibernate) settings,(uptional)-Show sql in console
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # (Optional) Custom path for the console
# spring.h2.console.path=/h2-console
spring.mongodb.uri=mongodb://localhost:27017/mydatabase
#logging
logging.level.org.springframework.security=DEBUG
# optionally
spring.mongodb.username=myuser
spring.mongodb.password=mypass
spring.mongodb.database=mydatabase
